### ISSUE TITLE
Homey Bridge

### ISSUE THREAD

**Issue by HertogAlva** [gruijter/com.plugwise.smile#17]
Hi,

I have bought the Plugwise Smile P1 and thought I could you it with Homey.
When I wanted to use the Plugwise Smile P1 I saw it is only available for the Homey Pro.
Could say if it will be available in the (near) future for Homey Bridge as well?

Best regard,

Michel Stroober
michelstroober@gmail.com

**Comment by gruijter** [comment]
Hi Michel,

No unfortunately the bridge does not work with wifi/local network devices (and the Smile P1 is a wifi/local network device). So only the Pro is an option for you then. Maybe Athom is willing to swap it around since the difference between homey, homey bridge and homy pro is not always obvious to everyone.
